4_flask_app/flask_app/my_app/__init__.py
from flask import Flask

from my_app.products.views import products

app = Flask(__name__)


# Importar vistas
app.register_blueprint(products)

@app.template_filter('mydouble')
def mydouble_filter(n:int):
    return n*2

4_flask_app/flask_app/my_app/products/__init__.py
# No tiene contenido

# Es necesario para crear una aplicación modular en flask o python

4_flask_app/flask_app/my_app/products/views.py
from flask import Blueprint, render_template
# TODO: werkzeug.exceptions es necesario apra importar la funcion abort,
# En el curso esta desactualizado o se esta utilizando una version antiguan en el proyecto
from werkzeug.exceptions import abort


from my_app.products.model.products import PRODUCTS

products = Blueprint('products', __name__)


@products.route('/')
@products.route('/home')
def index():
    return render_template('products/index.html', products = PRODUCTS)


@products.route('/show/<int:id>')
def show(id):
    product = PRODUCTS.get(id)
    if not product:
        abort(401)

    return render_template('products/show.html', product = product)

@products.route('/filter')
@products.route('/filter/<int:id>')
def filter(id):
    product = PRODUCTS.get(id)
    return render_template('products/filter.html', product = product)


@products.app_template_filter('iva')
def iva_filter(product):
    if product['price']:
        return product['price'] * .20 + product['price']
    return "sin precio"

4_flask_app/flask_app/my_app/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD</title>
</head>
<body>
    <header> Header of the app </header>
        {% block container %}
        
        {% endblock %}
    <footer> Footer </footer>
</body>
</html>

4_flask_app/flask_app/my_app/templates/products/filter.html
<h3> {{ product['name'] }} </h3>

<p> {{ product['category'] }} </p>
<p> $ {{ product['price'] }} </p>

<p> Filter default: {{ product['price'] | default('Sin precio', True) }} </p>

<p>filter safe: {{ "<h1>Hola mundo</h1>" | safe }}</p>
<p>filter truncate: {{ "Descripción bastante largo para una prueba para el filtro de truncate" | truncate(23) }}</p>
<p>filter count: {{ "Descripción bastante largo para una prueba para el filtro de truncate" | count }}</p>
<p>filter float: {{ 70 | float }}</p>
<p>filter int: {{ 70.87 | int }}</p> 
<p>filter round: {{ 3.1415926535 | round(3) }}</p> 
<p>filter join: {{ ["iPhone", "iPad"] | join(", ") }}</p> 
<p>filter length: {{ ["iPhone", "iPad"] | length }}</p> 
<p>filter tojson: {{ { 'offer': false, 'price': 50.5, 'K': 45 } | tojson }}</p> 

<p>filter custom global {{ 50 | mydouble  }}</p> 
<p>filter custom local {{ product | iva }}</p> 

4_flask_app/flask_app/my_app/templates/products/index.html
{% extends 'layout/base.html' %}
    {% block container %}
        {% for key, product in products.items() %}
            <div>
                <a href="{{ url_for('products.show', id = key) }}">
                    {{ loop.cycle('impar', 'par', 'otro') }}
                    {{ product['name'] }}
                </a>
                {{ loop.index }}
                {{ loop.index0 }}
                {{ loop.revindex }}
                {{ loop.first }}
                {{ loop.last }}
                {{ loop.previtem }}
            </div>
        {% endfor %}
    {% endblock %}

4_flask_app/flask_app/my_app/templates/products/show.html
{% block container %}
    <h3> {{ product['name'] }} </h3>

    <p> {{ product['category'] }} </p>
    <p> $ {{ product['price'] }} </p>
    {% if product['price'] >= 1000 %}
        <p>Precio regular</p>
        {% else %}
            <p>Precio oferta</p>
    {% endif %}

{% endblock %}